version: "3"

services:

  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxd

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb

volumes:
  influxdb:
